name: CI

on:
  push:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifact
        path: requirements.txt

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
